language: python
sudo: required
install:
    - pip install -r requirements.txt
    - mkdir -p vendor
    - pushd vendor
    - |
        if [ ! -f /usr/local/lib/liblept.so.5.0.1 ] || (git log -n1 | grep -q redo-lep); then
            curl -Lo leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/1.74.4.tar.gz
            tar xzf leptonica.tar.gz
            cd leptonica-1.74.4
            mkdir -p $HOME/local
            autoreconf --install
            ./configure
            make -j
            sudo make install
            cd ..
        fi
    - |
        if [ ! -f /usr/local/bin/tesseract ] || (git log -n1 | grep -q redo-tess); then
            curl -Lo tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/3.05.01.tar.gz
            tar xzf tesseract.tar.gz
            cd tesseract-3.05.01
            echo 'tesseract_LDADD += $(LEPTONICA_LIBS)' >> api/Makefile.am
            ./autogen.sh
            ./configure
            make -j
            sudo make install
            which tesseract || echo "Can't find tesseract in PATH"
        fi
    - mkdir -p $HOME/tessdata
    - cd $HOME/tessdata
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.tesseract_cube.nn
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.word-freq
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.size
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.params
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.nn
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.lm
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.fold
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.bigrams
    - popd
script: pytest -vv
python:
    # - "2.7"
    # - "3.2"
    # - "3.3"
    # - "3.4"
    - "3.5"
    # - "3.6"
    # - "nightly"
    # - "pypy"
    # - "pypy3"
cache:
    directories:
        - vendor
        - $HOME/.cache/pip
        - $HOME/tessdata
addons:
    apt:
        packages:
            - g++
            - autoconf
            - automake
            - libtool
            - autoconf-archive
            - pkg-config
            - libpng12-dev
            - libjpeg8-dev
            - libtiff5-dev
            - zlib1g-dev
