language: python
sudo: required
install:
    - pip install -r requirements.txt
    - mkdir vendor
    - cd vendor
    - curl -Lo leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/1.74.1.tar.gz
    - tar xzf leptonica.tar.gz
    - cd leptonica-1.74.1
    - mkdir -p $HOME/local
    - autoreconf --install
    - ./configure
    - make
    - sudo make install
    - cd ..
    - curl -Lo tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/3.05.01.tar.gz
    - tar xzf tesseract.tar.gz
    - cd tesseract-3.05.01
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - mkdir -p $HOME/tessdata
    - cd $HOME/tessdata
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.tesseract_cube.nn
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.word-freq
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.size
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.params
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.nn
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.lm
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.fold
    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.bigrams
    - export PATH=$PATH:$HOME/local/bin
script: pytest -vv
python:
    # - "2.7"
    # - "3.2"
    # - "3.3"
    # - "3.4"
    - "3.5"
    # - "3.6"
    # - "nightly"
    # - "pypy"
    # - "pypy3"
cache:
    directories:
        - vendor
        - $HOME/.cache/pip
addons:
    apt:
        packages:
            - g++
            - autoconf
            - automake
            - libtool
            - autoconf-archive
            - pkg-config
            - libpng12-dev
            - libjpeg8-dev
            - libtiff5-dev
            - zlib1g-dev
